package com.vitwo.battle;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public class TrainerPool {
    private static final Random RANDOM = new Random();

    public static final String[] TRAINERS = {
        "Aaron",
        "Ace Trainer Abel",
        "Ace Trainer Alexa",
        "Ace Trainer Alicia",
        "Ace Trainer Allen",
        "Ace Trainer Alyssa",
        "Ace Trainer Andrew",
        "Ace Trainer Anton",
        "Ace Trainer Ariana",
        "Ace Trainer Arthur",
        "Ace Trainer Austina",
        "Ace Trainer Barry",
        "Ace Trainer Berke",
        "Ace Trainer Blake",
        "Ace Trainer Brandi",
        "Ace Trainer Breanna",
        "Ace Trainer Brenda",
        "Ace Trainer Brenna",
        "Ace Trainer Brooke",
        "Ace Trainer Caroline",
        "Ace Trainer Catherine",
        "Ace Trainer Cesar",
        "Ace Trainer Clarice",
        "Ace Trainer Colby",
        "Ace Trainer Dalton",
        "Ace Trainer Dana",
        "Ace Trainer Deanna",
        "Ace Trainer Dennis",
        "Ace Trainer Destiny",
        "Ace Trainer Ernest",
        "Ace Trainer Felix",
        "Ace Trainer Garrett",
        "Ace Trainer George",
        "Ace Trainer Gilbert",
        "Ace Trainer Graham",
        "Ace Trainer Henry",
        "Ace Trainer Isaiah",
        "Ace Trainer Jake",
        "Ace Trainer Jamie",
        "Ace Trainer Janny",
        "Ace Trainer Jasmin",
        "Ace Trainer Jonah",
        "Ace Trainer Jose",
        "Ace Trainer Julie",
        "Ace Trainer Kassandra",
        "Ace Trainer Keenan",
        "Ace Trainer Laura",
        "Ace Trainer Leroy",
        "Ace Trainer Maria",
        "Ace Trainer Mariah",
        "Ace Trainer Mary",
        "Ace Trainer Maya",
        "Ace Trainer Meagan",
        "Ace Trainer Micah",
        "Ace Trainer Michelle",
        "Ace Trainer Mikayla",
        "Ace Trainer Monique",
        "Ace Trainer Naomi",
        "Ace Trainer Natasha",
        "Ace Trainer Nick",
        "Ace Trainer Olivia",
        "Ace Trainer Omar",
        "Ace Trainer Owen",
        "Ace Trainer Paul",
        "Ace Trainer Quinn",
        "Ace Trainer Rodolfo",
        "Ace Trainer Rolando",
        "Ace Trainer Ruben",
        "Ace Trainer Runan",
        "Ace Trainer Samantha",
        "Ace Trainer Samuel",
        "Ace Trainer Sandra",
        "Ace Trainer Saul",
        "Ace Trainer Savannah",
        "Ace Trainer Sergio",
        "Ace Trainer Shannon",
        "Ace Trainer Sharon",
        "Ace Trainer Skyler",
        "Ace Trainer Stefan",
        "Ace Trainer Sydney",
        "Ace Trainer Symes",
        "Ace Trainer Warren",
        "Ace Trainer Wilton",
        "Ace Trainer Yuji",
        "Ace Trainer Zachery",
        "Agatha",
        "Aroma Lady Alison",
        "Aroma Lady Angela",
        "Aroma Lady Elizabeth",
        "Aroma Lady Hannah",
        "Aroma Lady Jenna",
        "Aroma Lady Miah",
        "Aroma Lady Nikki",
        "Aroma Lady Rose",
        "Aroma Lady Teighler",
        "Aroma Lady Violet",
        "Artist Ismael",
        "Artist Kevin",
        "Artist William",
        "Battle Girl Helen",
        "Battle Girl Kelsey",
        "Battle Girl Tylor",
        "Battleground Alice",
        "Battleground Benjamin",
        "Battleground Big Mo",
        "Battleground Mel",
        "Battleground Tessy",
        "Battleground Vega",
        "Beauty Bridget",
        "Beauty Cyndy",
        "Beauty Devon",
        "Beauty Gabriella",
        "Beauty Grace",
        "Beauty Harley",
        "Beauty Lauren",
        "Beauty Lindsay",
        "Beauty Lola",
        "Beauty Lori",
        "Beauty Nicola",
        "Beauty Olivia",
        "Beauty Sheila",
        "Beauty Tamia",
        "Bertha",
        "Biker",
        "Biker Alex",
        "Biker Billy",
        "Biker Ernest",
        "Biker Gerald",
        "Biker Goon",
        "Biker Hideo",
        "Biker Isaac",
        "Biker Jared",
        "Biker Jaren",
        "Biker Jaxon",
        "Biker Lao",
        "Biker Lukas",
        "Biker Malik",
        "Biker Nikolas",
        "Biker Ricardo",
        "Biker Ruben",
        "Biker Virgil",
        "Biker William",
        "Bird Keeper Alexandra",
        "Bird Keeper Audrey",
        "Bird Keeper Autumn",
        "Bird Keeper Beck",
        "Bird Keeper Benny",
        "Bird Keeper Brianna",
        "Bird Keeper Carter",
        "Bird Keeper Chaz",
        "Bird Keeper Chester",
        "Bird Keeper Donald",
        "Bird Keeper Edwin",
        "Bird Keeper Geneva",
        "Bird Keeper Hana",
        "Bird Keeper Harold",
        "Bird Keeper Jacob",
        "Bird Keeper Katherine",
        "Bird Keeper Keith",
        "Bird Keeper Krystal",
        "Bird Keeper Marlon",
        "Bird Keeper Milo",
        "Bird Keeper Mitch",
        "Bird Keeper Perry",
        "Bird Keeper Reed",
        "Bird Keeper Robert",
        "Bird Keeper Roger",
        "Bird Keeper Sebastian",
        "Black Belt Aaron",
        "Black Belt Adam",
        "Black Belt Atsushi",
        "Black Belt Carl",
        "Black Belt Colby",
        "Black Belt Daisuke",
        "Black Belt Darren",
        "Black Belt David",
        "Black Belt Davon",
        "Black Belt Derek",
        "Black Belt Eddie",
        "Black Belt Gregory",
        "Black Belt Griffin",
        "Black Belt Hideki",
        "Black Belt Hitoshi",
        "Black Belt Hugh",
        "Black Belt Jarrett",
        "Black Belt Jeffery",
        "Black Belt Kendal",
        "Black Belt Kiyo",
        "Black Belt Kyle",
        "Black Belt Luke",
        "Black Belt Mike",
        "Black Belt Miles",
        "Black Belt Nathaniel",
        "Black Belt Philip",
        "Black Belt Rafael",
        "Black Belt Ray",
        "Black Belt Ricky",
        "Black Belt Sean",
        "Black Belt Shea",
        "Black Belt Takashi",
        "Black Belt Willie",
        "Black Emboar James",
        "Black Ferrothorn Barbs",
        "Black Ferrothorn Bullo",
        "Black Ferrothorn Chad",
        "Black Ferrothorn Rory",
        "Boss Giovanni",
        "Boss Thug",
        "Boss Zeph",
        "Breeder Alize",
        "Breeder Allison",
        "Breeder Annie",
        "Breeder Bethany",
        "Brock",
        "Bruno",
        "Bug Catcher",
        "Bug Catcher Anthony",
        "Bug Catcher Brandon",
        "Bug Catcher Brent",
        "Bug Catcher Cale",
        "Bug Catcher Charlie",
        "Bug Catcher Colton",
        "Bug Catcher Conner",
        "Bug Catcher Donald",
        "Bug Catcher Doug",
        "Bug Catcher Elijah",
        "Bug Catcher Garret",
        "Bug Catcher Greg",
        "Bug Catcher Jack",
        "Bug Catcher James",
        "Bug Catcher Jonah",
        "Bug Catcher Keigo",
        "Bug Catcher Kent",
        "Bug Catcher Phillip",
        "Bug Catcher Rick",
        "Bug Catcher Robby",
        "Bug Catcher Sammy",
        "Bug Catcher Vance",
        "Bugsy",
        "Burglar",
        "Burglar Arnie",
        "Burglar Dusty",
        "Burglar Lewis",
        "Burglar Quinn",
        "Burglar Ramon",
        "Burglar Simon",
        "Burglar Switzer",
        "Byron",
        "Cameraman Darryl",
        "Cameraman Tevin",
        "Camper Anthony",
        "Camper Bryce",
        "Camper Chris",
        "Camper Curtis",
        "Camper Diego",
        "Camper Drew",
        "Camper Ethan",
        "Camper Flint",
        "Camper Jacob",
        "Camper Jeff",
        "Camper Justin",
        "Camper Lawrence",
        "Camper Liam",
        "Camper Parker",
        "Camper Ricky",
        "Camper Riley",
        "Camper Shane",
        "Camper Zackary",
        "Candice",
        "Champion Cynthia",
        "Champion Jax",
        "Champion Terry",
        "Channeler",
        "Channeler Amanda",
        "Channeler Angelica",
        "Channeler Carly",
        "Channeler Emilia",
        "Channeler Hope",
        "Channeler Janae",
        "Channeler Jennifer",
        "Channeler Jody",
        "Channeler Karina",
        "Channeler Laurel",
        "Channeler Patricia",
        "Channeler Paula",
        "Channeler Rachel",
        "Channeler Ruth",
        "Channeler Stacy",
        "Channeler Tammy",
        "Channeler Tasha",
        "Chuck",
        "Clair",
        "Clown Lee",
        "Collector Brady",
        "Collector Dominique",
        "Collector Douglas",
        "Collector Edwin",
        "Collector Eugene",
        "Collector Fernando",
        "Collector Ivan",
        "Collector Jamal",
        "Collector Terry",
        "Commander Jupiter",
        "Commander Mars",
        "Commander Saturn",
        "Commanders Mars & Jupiter",
        "Cool Couple Lex & Nya",
        "Cool Couple Ray & Tyra",
        "Cowgirl Shelley",
        "Crush Girl Cyndy",
        "Crush Girl Jocelyn",
        "Crush Girl Sharon",
        "Crush Girl Tanya",
        "Crush Kin Mik & Kia",
        "Crush Kin Ron & Mya",
        "Cue Ball Camron",
        "Cue Ball Chase",
        "Cue Ball Corey",
        "Cue Ball Isaiah",
        "Cue Ball Jamal",
        "Cue Ball Koji",
        "Cue Ball Luke",
        "Cue Ball Raul",
        "Cue Ball Zeek",
        "Cyclist Axel",
        "Cyclist James",
        "Cyclist John",
        "Cyclist Kayla",
        "Cyclist Megan",
        "Cyclist Nicole",
        "Cyclist Rachel",
        "Cyclist Ryan",
        "Cynthia",
        "Double Team Al",
        "Double Team Jen",
        "Double Team Jen & Zac",
        "Double Team Jo",
        "Double Team Jo & Pat",
        "Double Team Kay",
        "Double Team Pat",
        "Double Team Zac",
        "Dragon Tamer Andre",
        "Dragon Tamer Clinton",
        "Dragon Tamer Darien",
        "Dragon Tamer Drake",
        "Dragon Tamer Geoffrey",
        "Dragon Tamer Hayden",
        "Dragon Tamer Joe",
        "Dragon Tamer Keegan",
        "Dragon Tamer Kenny",
        "Dragon Tamer Patrick",
        "Dragon Tamer Ramiro",
        "Dragon Tamer Stanley",
        "Elite Four Aaron",
        "Elite Four Agatha",
        "Elite Four Arabella",
        "Elite Four Bertha",
        "Elite Four Bruno",
        "Elite Four Elias",
        "Elite Four Flint",
        "Elite Four Lance",
        "Elite Four Lorelei",
        "Elite Four Lucian",
        "Elite Four Moleman",
        "Elite Four Penny",
        "Engineer Baily",
        "Engineer Bernie",
        "Engineer Braxton",
        "Erika",
        "Ex-Shadow Admin Marlon",
        "Expert Kenlawa",
        "Expert LanceRe",
        "Expert Ryuzoji",
        "Falkner",
        "Fantina",
        "Fisher Alec",
        "Fisher Andrew",
        "Fisher Brett",
        "Fisher Cameron",
        "Fisher Cody",
        "Fisher Cole",
        "Fisher Cory",
        "Fisher Erick",
        "Fisher George",
        "Fisher Joseph",
        "Fisher Juan",
        "Fisher Kenneth",
        "Fisher Luc",
        "Fisher Miguel",
        "Fisher Travis",
        "Fisher Walter",
        "Fisher Zachary",
        "Fisherman Andrew",
        "Fisherman Barny",
        "Fisherman Chip",
        "Fisherman Claude",
        "Fisherman Dale",
        "Fisherman Elliot",
        "Fisherman Hank",
        "Fisherman Ned",
        "Fisherman Nolan",
        "Fisherman Ronald",
        "Fisherman Tommy",
        "Fisherman Tylor",
        "Fisherman Wade",
        "Flint",
        "Friendly Coach (Atk)",
        "Friendly Coach (Def)",
        "Friendly Coach (Hp)",
        "Friendly Coach (Spa)",
        "Friendly Coach (Spd)",
        "Friendly Coach (Spe)",
        "Friendly Maniac",
        "Friendly Teacher",
        "Friendly Thug",
        "GAME FREAK’s Morimoto",
        "Gambler",
        "Gambler Darian",
        "Gambler Dirk",
        "Gambler Hugo",
        "Gambler Jasper",
        "Gambler Rich",
        "Gambler Stan",
        "Gardenia",
        "Gatekeeper Logan",
        "Gatekeeper Owen",
        "Gentleman Arthur",
        "Gentleman Brooks",
        "Gentleman Clifford",
        "Gentleman Jeremy",
        "Gentleman Komodo",
        "Gentleman Lamar",
        "Gentleman Leonardo",
        "Gentleman Norton",
        "Gentleman Thomas",
        "Gentleman Tucker",
        "Gentleman Walter",
        "Giovanni",
        "Guitarist Arturo",
        "Guitarist Jerry",
        "Guitarist Lonnie",
        "Guitarist Preston",
        "Guitarist Tony",
        "Gym Leader Byron",
        "Gym Leader Candice",
        "Gym Leader Fantina",
        "Gym Leader Gardenia",
        "Gym Leader Maylene",
        "Gym Leader Roark",
        "Gym Leader Volkner",
        "Gym Leader Wake",
        "Hiker Alan",
        "Hiker Alexander",
        "Hiker Allen",
        "Hiker Brice",
        "Hiker Clark",
        "Hiker Damon",
        "Hiker Daniel",
        "Hiker Daryl",
        "Hiker Dudley",
        "Hiker Earl",
        "Hiker Eric",
        "Hiker Franklin",
        "Hiker Jeremy",
        "Hiker Jonathan",
        "Hiker Justin",
        "Hiker Kevyn",
        "Hiker Lenny",
        "Hiker Lorenzo",
        "Hiker Louis",
        "Hiker Lucas",
        "Hiker Marcos",
        "Hiker Maurice",
        "Hiker Nicholas",
        "Hiker Nob",
        "Hiker Oliver",
        "Hiker Reginald",
        "Hiker Robert",
        "Hiker Theodore",
        "Hiker Trent",
        "Hiker Wayne",
        "Idol Grace",
        "Interviewers Oli",
        "Interviewers Oli & Roxy",
        "Interviewers Roxy",
        "Jasmine",
        "Jogger Craig",
        "Jogger Raul",
        "Jogger Richard",
        "Jogger Scott",
        "Jogger Wyatt",
        "Juggler Dalton",
        "Juggler Edward",
        "Juggler Gregory",
        "Juggler Kayden",
        "Juggler Kirk",
        "Juggler Mason",
        "Juggler Nate",
        "Juggler Nelson",
        "Juggler Shawn",
        "Lady Gillian",
        "Lady Jacki",
        "Lady Kylie",
        "Lady Melissa",
        "Lady Selphy",
        "Lance",
        "Lass Ali",
        "Lass Andrea",
        "Lass Ann",
        "Lass Anne",
        "Lass Blythe",
        "Lass Briana",
        "Lass Caroline",
        "Lass Cassidy",
        "Lass Crissy",
        "Lass Dalia",
        "Lass Dawn",
        "Lass Haley",
        "Lass Iris",
        "Lass Janice",
        "Lass Joana",
        "Lass Julia",
        "Lass Kaitlin",
        "Lass Kay",
        "Lass Lisa",
        "Lass Madeline",
        "Lass Megan",
        "Lass Miriam",
        "Lass Molly",
        "Lass Natalie",
        "Lass Paige",
        "Lass Reli",
        "Lass Robin",
        "Lass Sally",
        "Lass Samantha",
        "Lass Sarah",
        "Leader Alice",
        "Leader Benjamin",
        "Leader Big Mo",
        "Leader Blaine",
        "Leader Brock",
        "Leader Clair",
        "Leader Erika",
        "Leader Galavan",
        "Leader Koga",
        "Leader Lt. Surge",
        "Leader Mel",
        "Leader Mirskle",
        "Leader Misty",
        "Leader Sabrina",
        "Leader Tessy",
        "Leader Vega",
        "Light of Ruin Vega",
        "Lorelei",
        "Lt. Surge",
        "Lucian",
        "Madame Rebecca",
        "Madame Reina",
        "Maylene",
        "Mega Trainer Aloysius",
        "Mega Trainer Ernesto",
        "Mega Trainer Krystal",
        "Mega Trainer Lily",
        "Mega Trainer Mathis",
        "Mega Trainer Osean",
        "Mega Trainer Portia",
        "Mega Trainer Ravonna",
        "Mega Trainer Reena",
        "Mega Trainer Sterling",
        "Mega Trainer Timothy",
        "Mega Trainer Travon",
        "Mega Trainer Vivian",
        "Mega Trainer Yale",
        "Mike",
        "Misty",
        "Morty",
        "Nat",
        "Ninja Boy Antonio",
        "Ninja Boy Brennan",
        "Ninja Boy Bruce",
        "Ninja Boy Davey",
        "Ninja Boy Ethan",
        "Ninja Boy Fabian",
        "Ninja Boy Joel",
        "Ninja Boy Nathan",
        "Ninja Boy Nick",
        "Ninja Boy Zach",
        "PI Carlos",
        "PI Kendrick",
        "Painter Celina",
        "Painter Daisy",
        "Painter Edna",
        "Painter Rayna",
        "Parasol Lady Alexa",
        "Parasol Lady Sabrina",
        "Picnicker Alicia",
        "Picnicker Alma",
        "Picnicker Ana",
        "Picnicker Ariana",
        "Picnicker Becky",
        "Picnicker Caitlin",
        "Picnicker Carol",
        "Picnicker Celia",
        "Picnicker Cheyenne",
        "Picnicker Claire",
        "Picnicker Dana",
        "Picnicker Diana",
        "Picnicker Gwen",
        "Picnicker Hannah",
        "Picnicker Heidi",
        "Picnicker Irene",
        "Picnicker Isabelle",
        "Picnicker Karina",
        "Picnicker Kelsey",
        "Picnicker Kindra",
        "Picnicker Lauren",
        "Picnicker Leah",
        "Picnicker Marcy",
        "Picnicker Martha",
        "Picnicker Missy",
        "Picnicker Nancy",
        "Picnicker Siena",
        "Picnicker Sofia",
        "Picnicker Summer",
        "Picnicker Susie",
        "Picnicker Tina",
        "Picnicker Tori",
        "Picnicker Valerie",
        "Picnicker Yazmin",
        "Player Brendan",
        "Player Leaf",
        "Player May",
        "Player Red",
        "Poké Fan Leonard",
        "Poké Fan Meredith",
        "Poké Fan Rebekah",
        "Poké Kid Ariel",
        "Poké Kid Danielle",
        "Poké Kid Janet",
        "Poké Kid Meghan",
        "Pokéfan AgathaRe",
        "Pokémaniac Ashton",
        "Pokémaniac Cooprt",
        "Pokémaniac Dawson",
        "Pokémaniac Hector",
        "Pokémaniac Herman",
        "Pokémaniac Mark",
        "Pokémaniac Steve",
        "Pokémaniac Winston",
        "Pokémon Breeder Albert",
        "Pokémon Breeder Amber",
        "Pokémon Breeder Jennifer",
        "Pokémon Breeder Kahlil",
        "Pokémon Breeder Kaylee",
        "Pokémon Ranger Allison",
        "Pokémon Ranger Ashlee",
        "Pokémon Ranger Deshawn",
        "Pokémon Ranger Dwayne",
        "Pokémon Ranger Felicia",
        "Pokémon Ranger Jeffrey",
        "Pokémon Ranger Krista",
        "Pokémon Ranger Kyler",
        "Pokémon Ranger Taylor",
        "Pokémon Trainer Buck",
        "Pokémon Trainer Cedric",
        "Pokémon Trainer Cheryl",
        "Pokémon Trainer Dawn",
        "Pokémon Trainer Lucas",
        "Pokémon Trainer Marley",
        "Pokémon Trainer Mira",
        "Pokémon Trainer Riley",
        "Police Officer Alex",
        "Police Officer Bobby",
        "Police Officer Caleb",
        "Police Officer Danny",
        "Police Officer Dylan",
        "Police Officer Thomas",
        "Prof. Prof. Oak",
        "Professor Oak",
        "Pryce",
        "Psychic Abigail",
        "Psychic Brittney",
        "Psychic Bryce",
        "Psychic Cameron",
        "Psychic Chelsey",
        "Psychic Corbin",
        "Psychic Daisy",
        "Psychic Dario",
        "Psychic Deandre",
        "Psychic Desiree",
        "Psychic Elijah",
        "Psychic Jaclyn",
        "Psychic Johan",
        "Psychic Kendra",
        "Psychic Kody",
        "Psychic Landon",
        "Psychic Laura",
        "Psychic Lindsey",
        "Psychic Maxwell",
        "Psychic Mitchell",
        "Psychic Preston",
        "Psychic Rachael",
        "Psychic Rodette",
        "Psychic Sterling",
        "Psychic Tyron",
        "Psychic Valencia",
        "Rancher Marco",
        "Ranchers Ava",
        "Ranchers Ava & Matt",
        "Ranchers Beth",
        "Ranchers Beth & Bob",
        "Ranchers Bob",
        "Ranchers Matt",
        "Ranger Beth",
        "Ranger Jackson",
        "Ranger Katelyn",
        "Ranger Madeline",
        "Ranger Nicolas",
        "Reporter Kinsey",
        "Reporter Valerie",
        "Rich Boy Jason",
        "Rich Boy Roman",
        "Rich Boy Trey",
        "Rival Terry",
        "Rival Wayne",
        "Roark",
        "Rocker Luca",
        "Rocker Randall",
        "Rocket Admin Archer",
        "Rocket Admin Ariana",
        "Rocket Admins Archer & Ariana",
        "Roughneck Kirby",
        "Ruin Admin Ivory",
        "Ruin Leader Aklove",
        "Ruin Mamoac Benjamin",
        "Ruin Mamoac Brandon",
        "Ruin Mamoac Foster",
        "Ruin Mamoac Larry",
        "Ruin Mamoac Lawson",
        "Ruin Mamoac Layton",
        "Ruin Mamoac Stanly",
        "Ruin Maniac Bryan",
        "Ruin Maniac Calvin",
        "Ruin Maniac Gerald",
        "Ruin Maniac Harry",
        "Ruin Maniac Hunter",
        "Ruin Maniac Karl",
        "Ruin Maniac Larry",
        "Sailor Damian",
        "Sailor Duncan",
        "Sailor Dwayne",
        "Sailor Dylan",
        "Sailor Edmond",
        "Sailor Huey",
        "Sailor Leonard",
        "Sailor Luther",
        "Sailor Marc",
        "Sailor Paul",
        "Sailor Phillip",
        "Sailor Samson",
        "Sailor Skyler",
        "Sailor Trevor",
        "Sailor Zachariah",
        "School Kid BrunoRe",
        "School Kid Chance",
        "School Kid Christine",
        "School Kid Esteban",
        "School Kid Forrest",
        "School Kid Harrison",
        "School Kid Mackenzie",
        "School Kid Tiera",
        "Science Society Scientist",
        "Scientist Beau",
        "Scientist Braydon",
        "Scientist Connor",
        "Scientist Darrius",
        "Scientist Ed",
        "Scientist Emilio",
        "Scientist Fredrick",
        "Scientist Gideon",
        "Scientist Ivan",
        "Scientist Jerry",
        "Scientist Jose",
        "Scientist Joshua",
        "Scientist Parkker",
        "Scientist Rodney",
        "Scientist Shaun",
        "Scientist Stefano",
        "Scientist Taylor",
        "Scientist Ted",
        "Scientist Travis",
        "Scientist Travon",
        "Shadow Admin Ivory",
        "Shadow Admin Ivory & Grunt",
        "Shadow Admin Marlon",
        "Shadow Admin Marlon & Grunt",
        "Shadow Grunt",
        "Silly Creator",
        "Silly Gambler",
        "Silly Gian",
        "Silly Jojo Fan",
        "Silly Kid",
        "Sinnoh Leader Candice",
        "Sis And Bro Ava & Geb",
        "Sis And Bro Lia & Luc",
        "Sis And Bro Lil & Ian",
        "Skier Andrea",
        "Skier Bjorn",
        "Skier Bradley",
        "Skier Edward",
        "Skier Kaitlyn",
        "Skier Lexie",
        "Skier Madison",
        "Skier Shawn",
        "Sucessor Maxima",
        "Sue",
        "Super Nerd Aavery",
        "Super Nerd Aidan",
        "Super Nerd Derek",
        "Super Nerd Erik",
        "Super Nerd Glenn",
        "Super Nerd Jovan",
        "Super Nerd Leslie",
        "Super Nerd Miguel",
        "Super Nerd Zac",
        "Swimmer Adrian",
        "Swimmer Aubree",
        "Swimmer Cassandra",
        "Swimmer Claire",
        "Swimmer Colton",
        "Swimmer Crystal",
        "Swimmer Dillon",
        "Swimmer Erica",
        "Swimmer Erik",
        "Swimmer Evan",
        "Swimmer Francisco",
        "Swimmer Gabrielle",
        "Swimmer Glenn",
        "Swimmer Haley",
        "Swimmer Jessica",
        "Swimmer Joanna",
        "Swimmer Katelyn",
        "Swimmer Kurt",
        "Swimmer Lydia",
        "Swimmer Mallory",
        "Swimmer Mary",
        "Swimmer Miranda",
        "Swimmer Oscar",
        "Swimmer Paige",
        "Swimmer Ricardo",
        "Swimmer Sam",
        "Swimmer Shelton",
        "Swimmer Sophia",
        "Swimmer Troy",
        "Swimmer Vanessa",
        "Swimmer Vincent",
        "Swimmer Wade",
        "Swimmer Wesley",
        "Swimmer♀ Abigail",
        "Swimmer♀ Alice",
        "Swimmer♀ Amara",
        "Swimmer♀ Anya",
        "Swimmer♀ Connie",
        "Swimmer♀ Denise",
        "Swimmer♀ Maria",
        "Swimmer♀ Melissa",
        "Swimmer♀ Nicole",
        "Swimmer♀ Nora",
        "Swimmer♀ Shirley",
        "Swimmer♀ Tiffany",
        "Swimmer♀ Tisha",
        "Swimmer♂ Axle",
        "Swimmer♂ Barry",
        "Swimmer♂ Darrin",
        "Swimmer♂ David",
        "Swimmer♂ Dean",
        "Swimmer♂ Douglas",
        "Swimmer♂ Finn",
        "Swimmer♂ Garrett",
        "Swimmer♂ Jack",
        "Swimmer♂ Jerome",
        "Swimmer♂ Luis",
        "Swimmer♂ Matthew",
        "Swimmer♂ Mymo",
        "Swimmer♂ Reece",
        "Swimmer♂ Richard",
        "Swimmer♂ Roland",
        "Swimmer♂ Samir",
        "Swimmer♂ Spencer",
        "Swimmer♂ Toby",
        "Swimmer♂ Tony",
        "Tamer Cole",
        "Tamer Edgar",
        "Tamer Evan",
        "Tamer Jason",
        "Tamer John",
        "Tamer Phil",
        "Tamer Vincent",
        "Team Galactic Boss Cyrus",
        "Team Galactic Grunt",
        "Team Rocket Admin",
        "Team Rocket Grunt",
        "Terror Granbull Gruff",
        "Title Defense Jax",
        "Title Defense Marlon",
        "Title Defense Milo",
        "Title Defense Rival Wayne",
        "Title Defense Solenk",
        "Title Defense Zeph",
        "Trainer Blue",
        "Trainer Brendan",
        "Trainer Cole",
        "Trainer Haley",
        "Trainer Ketchup",
        "Trainer May",
        "Trainer Red",
        "Trainer Sam",
        "Trainer Shelly",
        "Tuber Alexis",
        "Tuber Amira",
        "Tuber Caitlyn",
        "Tuber Chelsea",
        "Tuber Conner",
        "Tuber Holly",
        "Tuber Jacky",
        "Tuber Jared",
        "Tuber Mariel",
        "Tuber Trenton",
        "Twin Emma",
        "Twin Lil",
        "Twin Liv",
        "Twin Liz",
        "Twin Teri",
        "Twin Tia",
        "Twins Eli & Anne",
        "Twins Emma & Lil",
        "Twins Joy & Meg",
        "Twins Kiri & Jan",
        "Twins Liv & Liz",
        "Twins Miu & Mia",
        "Twins Teri & Tia",
        "Veteran Armando",
        "Veteran Brenden",
        "Veteran Brian",
        "Veteran Clayton",
        "Veteran Edgar",
        "Veteran Emanuel",
        "Veteran Grant",
        "Veteran Harlan",
        "Veteran Terrell",
        "Volkner",
        "Waitress Kati",
        "Wake",
        "Whitney",
        "Worker Braden",
        "Worker Brendon",
        "Worker Colin",
        "Worker Conrad",
        "Worker Dillan",
        "Worker Gary",
        "Worker Gerardo",
        "Worker Holden",
        "Worker Jackson",
        "Worker Mason",
        "Worker Quentin",
        "Worker Willy",
        "Young Couple Eve & Jon",
        "Young Couple Gia & Jes",
        "Young Couple Lea & Jed",
        "Young Couple Mike & Nat",
        "Young Couple Sue & Ty",
        "Youngster Austin",
        "Youngster Ben",
        "Youngster Calvin",
        "Youngster Chad",
        "Youngster Cordell",
        "Youngster Dallas",
        "Youngster Dan",
        "Youngster Darius",
        "Youngster Dave",
        "Youngster Destin",
        "Youngster Dillon",
        "Youngster Donny",
        "Youngster Eddie",
        "Youngster Joey",
        "Youngster Johnson",
        "Youngster Jonathon",
        "Youngster Josh",
        "Youngster LanceRe",
        "Youngster Logan",
        "Youngster Michael",
        "Youngster Nash",
        "Youngster Oliver",
        "Youngster Sebastian",
        "Youngster Timmy",
        "Youngster Tristan",
        "Youngster Tyler",
        "Youngster Wayne",
        "Youngster Yasu",
    };

    // Competitive Tier 1 (Floors 1-25)
    public static final List<String> TIER_1_SPECIES = List.of(
            "arcanine", "starmie", "breloom", "raichu", "nidoking", "scizor", "aerodactyl", "gardevoir",
            "swampert", "flygon", "lucario", "gengar", "electivire", "magmortar", "roserade", "togekiss",
            "gallade", "mamoswine", "kingdra", "milotic", "heracross", "crobat", "blaziken", "sceptile",
            "feraligatr", "typhlosion", "venusaur", "charizard", "blastoise", "jolteon", "vaporeon", "espeon",
            "umbreon", "sylveon", "glaceon", "leafeon", "snorlax", "gyarados", "lapras", "drapion"
    );

    // Competitive Tier 2 (Floors 26-50)
    public static final List<String> TIER_2_SPECIES = List.of(
            "garchomp", "tyranitar", "dragonite", "hydreigon", "volcarona", "excadrill", "aegislash",
            "greninja", "dragapult", "baxcalibur", "toxapex", "ferrothorn", "gliscor", "blissey",
            "corviknight", "skeledirge", "annihilape", "kingambit", "great_tusk", "iron_valiant",
            "garganacl", "gholdengo", "ting_lu", "iron_treads", "iron_moth", "walking_wake",
            "metagross", "salamence", "kommo-o", "goodra", "haxorus", "chandelure", "darmanitan"
    );

    // Competitive Tier 3 (Floors 51-75)
    public static final List<String> TIER_3_SPECIES = List.of(
            "urshifu", "heatran", "landorus", "thundurus", "tornadus", "zapdos", "moltres", "articuno",
            "raikou", "entei", "suicune", "latios", "latias", "regieleki", "regidrago", "terrakion",
            "cobalion", "virizion", "keldeo", "ogerpon", "flutter_mane", "iron_bundle", "chien_pao",
            "chi_yu", "roaring_moon", "iron_hands", "cresselia", "darkrai", "shaymin", "victini"
    );

    // Mythical & Sovereign Pool (Floors 76-100)
    public static final List<String> SOVEREIGN_SPECIES = List.of(
            "rayquaza", "mewtwo", "arceus", "giratina", "dialga", "palkia", "kyogre", "groudon",
            "zacian", "zamazenta", "eternatus", "calyrex", "spectrier", "glastrier", "koraidon",
            "miraidon", "necrozma", "solgaleo", "lunala", "zygarde", "xerneas", "yveltal",
            "reshiram", "zekrom", "kyurem", "ho-oh", "lugia", "deoxys", "marshadow"
    );

    // Weather & Synergy Strategy Archetypes (Floors 51+)
    public static final List<String> RAIN_ARCHETYPE = List.of("pelipper", "kingdra", "barraskewda", "zapdos", "urshifu", "archaludon");
    public static final List<String> SUN_ARCHETYPE = List.of("torkoal", "chi_yu", "flutter_mane", "walking_wake", "roaring_moon", "great_tusk");
    public static final List<String> TRICK_ROOM_ARCHETYPE = List.of("hatterene", "ursaluna", "torkoal", "kingambit", "cresselia", "armarouge");
    public static final List<String> STALL_HAZARD_ARCHETYPE = List.of("ting_lu", "toxapex", "gliscor", "corviknight", "blissey", "garganacl");

    public static final List<String> COMPETITIVE_HELD_ITEMS = List.of(
            "cobblemon:focus_sash", "cobblemon:choice_scarf", "cobblemon:choice_band", "cobblemon:choice_specs",
            "cobblemon:life_orb", "cobblemon:assault_vest", "cobblemon:heavy_duty_boots", "cobblemon:booster_energy",
            "cobblemon:leftovers", "cobblemon:rocky_helmet", "cobblemon:sitrus_berry", "cobblemon:lum_berry"
    );

    public static String getRandomTrainerName(int floor) {
        if (floor >= 100) return "§4§lGENESIS ARCEUS";
        if (floor >= 91) {
            String[] mythicalTitles = {
                    "Origin Sovereign Giratina", "Temporal Sovereign Dialga", "Spatial Sovereign Palkia",
                    "Sky Sovereign Mega Rayquaza", "Sea Sovereign Primal Kyogre", "Earth Sovereign Primal Groudon",
                    "Crown Sovereign Calyrex Shadow", "Hero Sovereign Crowned Zacian", "Cosmic Sovereign Ultra Necrozma"
            };
            return mythicalTitles[(floor - 91) % mythicalTitles.length];
        }
        int idx = (Math.abs(floor * 37 + (int) System.currentTimeMillis() / 60000)) % TRAINERS.length;
        return TRAINERS[idx];
    }

    public static List<String> generateDynamicTeam(int floor) {
        List<String> team = new ArrayList<>();

        if (floor >= 91) {
            List<String> shuffled = new ArrayList<>(SOVEREIGN_SPECIES);
            Collections.shuffle(shuffled, RANDOM);
            for (int i = 0; i < 6; i++) team.add(shuffled.get(i % shuffled.size()));
            return team;
        }

        // Higher floors (51-90) have a 50% chance to roll a dedicated weather/strategy synergy team
        if (floor >= 51 && RANDOM.nextInt(100) < 50) {
            int archetype = RANDOM.nextInt(4);
            return switch (archetype) {
                case 0 -> new ArrayList<>(RAIN_ARCHETYPE);
                case 1 -> new ArrayList<>(SUN_ARCHETYPE);
                case 2 -> new ArrayList<>(TRICK_ROOM_ARCHETYPE);
                default -> new ArrayList<>(STALL_HAZARD_ARCHETYPE);
            };
        }

        List<String> pool;
        if (floor >= 76) {
            pool = new ArrayList<>(TIER_3_SPECIES);
            pool.addAll(SOVEREIGN_SPECIES.subList(0, 8));
        } else if (floor >= 51) {
            pool = new ArrayList<>(TIER_2_SPECIES);
            pool.addAll(TIER_3_SPECIES.subList(0, 10));
        } else if (floor >= 26) {
            pool = new ArrayList<>(TIER_1_SPECIES);
            pool.addAll(TIER_2_SPECIES);
        } else {
            pool = new ArrayList<>(TIER_1_SPECIES);
        }
        Collections.shuffle(pool, RANDOM);
        for (int i = 0; i < 6; i++) {
            team.add(pool.get(i % pool.size()));
        }
        return team;
    }

    public static String getRandomCompetitiveItem() {
        return COMPETITIVE_HELD_ITEMS.get(RANDOM.nextInt(COMPETITIVE_HELD_ITEMS.size()));
    }
}
